### ISSUE TITLE
Missing a backslash in Dockerfile?

### ISSUE THREAD

**Issue by DanBodell** [OpenLoco/openloco-docker-build#13]
When I try and build the docker image from source, I get the compiler yelling at me that it doesn't know what clang is.  Adding a space and a backslash at the end of line 6 solved it for me, wasn't sure if that was universal or not. Figured I'd check before doing a pull request

**Comment by AaronVanGeffen** [comment]
You're totally right. The Dockerfile in the root of the repository is actually not the one we use for CI builds today. We use three Docker CI images, and the current ones are in the folder with the highest number, which is currently [version 7](https://github.com/OpenLoco/openloco-docker-build/tree/master/7).

I think we should probably delete the old, very dated Dockerfile at the root of the repository to prevent confusion. @janisozaur, what do you think?

**Comment by DanBodell** [comment]
I believe a quick little Readme.md file in the repo to explain how things are set up would go a long ways for people like me blindly grasping at making things work. Pretty much what you said Aaron would be enough to not blindly wander into depreciated docker files like me XD

**Comment by janisozaur** [comment]
Yes, this should get removed

**Comment by AaronVanGeffen** [comment]
Removed in f13ee17924f4cf5cc119549e028935597bca1dd4.
